<?xml version="1.0"?>
<package format="2">
  <name>warehouse_qmix</name>
  <version>0.1.0</version>
  <description>AGV QMIX warehouse Gazebo integration</description>
  <maintainer email="user@example.com">user</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>rospy</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>move_base_msgs</depend>
  <depend>actionlib</depend>
  <depend>tf</depend>
  <depend>wpb_mani_behaviors</depend>
  <depend>gazebo_ros</depend>
  <depend>map_server</depend>
  <depend>amcl</depend>
  <depend>move_base</depend>
</package>
